// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/check":{"get":{"description":"用户或管理员进入后显示所有的面试时间段表","produces":["application/json"],"tags":["公有"],"summary":"返回面试表","responses":{"200":{"description":"成功返回面试时间表","schema":{"$ref":"#/definitions/serializer.Response"}},"400":{"description":"请求失败","schema":{"$ref":"#/definitions/serializer.Response"}}}}},"/index":{"get":{"description":"返回首页 HTML 页面（服务端渲染）","produces":["text/html"],"tags":["公有"],"summary":"渲染首页","responses":{"200":{"description":"HTML 页面内容","schema":{"type":"string"}}}}},"/norouter":{"get":{"description":"路由未找到时返回自定义 404 页面","produces":["text/html"],"tags":["公有"],"summary":"404 页面","responses":{"200":{"description":"404 HTML 页面","schema":{"type":"string"}}}}}},"definitions":{"serializer.Response":{"type":"object","properties":{"data":{},"error":{"type":"string"},"msg":{"type":"string"},"status":{"type":"integer"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API",
	Description:      "acat recruit",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
